# Generated by Django 5.2.11 on 2026-02-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('descricao', models.TextField()),
                ('cor_neon', models.CharField(default='#8A2BE2', max_length=7)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
