# Generated by Django 5.2.11 on 2026-02-12 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo_texto', models.TextField()),
                ('video_url', models.URLField(blank=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='cursos.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('arquivo', models.FileField(upload_to='materiais/')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='cursos.curso')),
            ],
        ),
    ]
