# Generated by Django 5.2.11 on 2026-02-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_aluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_postagem', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Fotos da Galeria',
            },
        ),
    ]
