# Generated by Django 5.2.11 on 2026-02-13 17:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_galeria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='nome',
            new_name='titulo',
        ),
        migrations.AddField(
            model_name='material',
            name='data_upload',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material',
            name='arquivo',
            field=models.FileField(upload_to='materiais/pdf'),
        ),
    ]
