# Generated by Django 5.2.11 on 2026-02-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_rename_nome_material_titulo_material_data_upload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeria',
            name='imagem',
            field=models.ImageField(default='temp.jpg', upload_to='galeria/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='galeria',
            name='titulo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
