# Generated by Django 5.2.11 on 2026-02-14 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_galeria_imagem_galeria_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='material',
            name='curso',
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('ordem', models.PositiveIntegerField(default=1, help_text='Ordem de exibição (1, 2, 3...)')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='cursos.curso')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['ordem'],
            },
        ),
        migrations.AddField(
            model_name='aula',
            name='modulo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='cursos.modulo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='modulo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='cursos.modulo'),
            preserve_default=False,
        ),
    ]
