# Generated by Django 5.2.11 on 2026-02-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_remove_aula_curso_remove_material_curso_modulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='imagem_fundo',
            field=models.ImageField(blank=True, null=True, upload_to='cursos/capas/'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
