# Generated by Django 5.2.11 on 2026-02-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_curso_imagem_fundo_modulo_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='arquivo',
            field=models.FileField(upload_to='materiais/'),
        ),
    ]
