# Generated by Django 5.2.11 on 2026-02-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_alter_material_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='link_externo',
            field=models.URLField(blank=True, help_text='Link do YouTube ou Google Drive (compartilhado)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='materiais/'),
        ),
    ]
