# Generated by Django 5.2.11 on 2026-03-13 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0010_material_link_externo_alter_material_arquivo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aula',
            options={'ordering': ['ordem'], 'verbose_name': 'Aula', 'verbose_name_plural': 'Aulas'},
        ),
        migrations.AddField(
            model_name='aula',
            name='ordem',
            field=models.PositiveIntegerField(default=1, help_text='Ordem de exibição dentro do módulo'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
