# Generated by Django 5.2.11 on 2026-03-13 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0011_alter_aula_options_aula_ordem_alter_curso_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='tipo',
            field=models.CharField(choices=[('pdf', 'PDF / Partitura'), ('video', 'Vídeo (MP4)'), ('imagem', 'Imagem'), ('link', 'Link externo (YouTube / Drive)'), ('outro', 'Outro arquivo')], default='outro', help_text='Escolha o tipo do material para exibição correta na plataforma.', max_length=10),
        ),
        migrations.AlterField(
            model_name='aula',
            name='ordem',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='ordem',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
