# Generated by Django 5.2.11 on 2026-03-13 01:49

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0012_material_tipo_alter_aula_ordem_alter_modulo_ordem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='arquivo',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='materiais/'),
        ),
    ]
